local modload = "cron", "cron.entry", "schedule", "unschedule",
  "gpio", "HIGH", "LOW", "ALARM_AUTO",
  "mqtt.socket",
  "math", "floor", "unregister",
  "error", "self",
  "crypto.hash", "ws2812.buffer",
  "max", "rep", "get"

local ctfws = "ctfws", "ctfws_lcd",
  "setupD", "roundD", "rounds", "startT", "endT", "flagsN", "flagsR", "flagsY",
    "ter", "tercfg", "gamenr", "cbs",
  "times", "config", "deconfig", "setFlags", "setEndTime", "myTeam",
  "setTerritory", "reconfig",
  "endtime", "flags", "territory",
  "GAME NOT CONFIGURED!",
  "GAME OVER @ %02d:%02d", "GAME OVER",
  "START TIME IN FUTURE",
  "TIME IS UP",
  "CTFWS",
  "r", "y",
  "d", "w", "wd", "dw"

local lcdpreload =
  "define_char",
  "lcd", "mtmr", "ftmr", "fatmr", "dl_elapsed", "dl_elapsed", "dl_remain",
  "dl_round", "attnState", "reset", "drawTimes", "drawFlags", "drawMessage",
  "drawFlagsMessage", "UI",
  "% 4d:%02d.%d", "  %02d:%02d.%d", "%02d.%d", "%d", "%-20s",
  "%d\000: %s=%s %s=%s", "%d\000: %s=%s%s",
  " CMUKGB CTFWS TIMER ", "                    ",
  "GAME", "GAME %d", "SETUP", "SETUP %d",
  "START IN", "GAME END",
  "JB#   %d/%d :",
  "JB# %2d/%2d :",
  "R", "Y", ":"

local mainload =
  "lastMsgTime", "mqttUser", "main",
  "dprint", "mqc", "publish",
  "nwfmqtt.conf",
  "* * * * *",
  "ctfws/game/config",
  "ctfws/game/endtime",
  "ctfws/game/flags",
  "ctfws/game/message",
  "ctfws/game/message/jail",
  "none",
  "^%s*(%d+)%s+(%d+)%s+(%d+)%s+(%d+)%s+(%d+)%s+(%d+)%s+(%S+).*$",
  "^%s*(%d+)%s+(-?%d+)%s+(-?%d+).*$",
  "^%s*(%d+)%s*(.*)$",
  "^%s*%?.*$",
  "^ctfws/game/message",
  "MQTT", "MQTT CONNECTED", "MQTT Disconnected", "DHCP %s",
  "WIFI %s", "NET", "Trying reconn...",
  "alive", "beat %d %s"
